### ISSUE TITLE
lastAppendTime设置可能会延迟

### ISSUE THREAD

**Issue by Zzaniu** [go-kratos/aegis#17]
[func (r *RollingPolicy) apply(f func(offset int, val float64), val float64)](https://github.com/go-kratos/aegis/blob/201e1edc072a675842b7163b9b69cf34170c4049/pkg/window/policy.go?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L67)
这里如果timespan超过了r.size，会导致r.lastAppendTime设置的时间不对。 下面是修改过的代码
```go
func (r *RollingPolicy) apply(f func(offset int, val float64), val float64) {
	r.mu.Lock()
	defer r.mu.Unlock()

	// calculate current offset
	rawtimespan := r.timespan()
	if rawtimespan > 0 {
		start := (r.offset + 1) % r.size
		end := (r.offset + timespan) % r.size
                timespan := rawtimespan
		if rawtimespan > r.size {
			timespan = r.size
		}
		// reset the expired buckets
		r.window.ResetBuckets(start, timespan)
		r.offset = end
		r.lastAppendTime = r.lastAppendTime.Add(time.Duration(rawtimespan * int(r.bucketDuration)))
	}
	f(r.offset, val)
}
```

**Comment by kagaya85** [comment]
fixed by #24
