### ISSUE TITLE
bbr限流实现 maxInFlight 方法可能有误

### ISSUE THREAD

**Issue by DZGodly** [go-kratos/aegis#21]
https://github.com/go-kratos/aegis/blob/56c0fb5bebed5714030f14fec8b54c1873664893/ratelimit/bbr/bbr.go#L235
最后加的那个0.5是不是放错位置了。Floor函数返回的已经是一个整数值，在加 0.5 后，会被最外层的 int64() 截断吧

**Comment by haiyux** [comment]
> https://github.com/go-kratos/aegis/blob/56c0fb5bebed5714030f14fec8b54c1873664893/ratelimit/bbr/bbr.go#L235
> 
> 
> 最后加的那个0.5是不是放错位置了。Floor函数返回的已经是一个整数值，在加 0.5 后，会被最外层的 int64() 截断吧

+0.5 是为了向上取证

**Comment by DZGodly** [comment]
> > https://github.com/go-kratos/aegis/blob/56c0fb5bebed5714030f14fec8b54c1873664893/ratelimit/bbr/bbr.go#L235
> > 
> > 最后加的那个0.5是不是放错位置了。Floor函数返回的已经是一个整数值，在加 0.5 后，会被最外层的 int64() 截断吧
> 
> +0.5 是为了向上取整

加错位置了吧，应该先加 0.5 再进行 Floor 操作吧

**Comment by juwell** [comment]
why not use `math.Ceil()` to get value greater than or equal to x ?

the comment for `Ceil`

```golang
// Ceil returns the least integer value greater than or equal to x.
//
// Special cases are:
//	Ceil(±0) = ±0
//	Ceil(±Inf) = ±Inf
//	Ceil(NaN) = NaN
func Ceil(x float64) float64
```

**Comment by lxkaka** [comment]
not same with +0.5
