### ISSUE TITLE
window.Bucket为什么不直接使用数值类型统计

### ISSUE THREAD

**Issue by wangshuo5597** [go-kratos/aegis#22]
type Bucket struct {
	Points []float64 // 这里为什么要用切片类型呢？
	Count  int64
	next   *Bucket
}

Points 如果定义为数值类型会有什么坏处吗？看源码里也只使用Points[0]，这样的话为什么不直接用数值类型呢？

**Comment by wangshuo5597** [comment]
> 

type Bucket struct {
Points float64
Count int64
next *Bucket
}
我是说是否可以定位这样，因为bbr的allow里都是调用add方法，bucket本身也只有在Count==0的时候调用append一次，所以Points本身的长度不会超过1，这样的话为什么不直接用Points float64呢？

**Comment by pauky** [comment]
`Points`需要是slice类型，可以存储单个窗口内的多个指标值，方便后续对其进行最大值或最小值或平均值等转换。

**Comment by haiyux** [comment]
方便扩展
