### ISSUE TITLE
minRT in bbr may be wrong

### ISSUE THREAD

**Issue by pauky** [go-kratos/aegis#23]
https://github.com/go-kratos/aegis/blob/56c0fb5bebed5714030f14fec8b54c1873664893/ratelimit/bbr/bbr.go#L219

If you want to count the avg of single window with all points, you should use this: 
```
avg := total / float64(len(bucket.Points))
```

**Comment by haiyux** [comment]
`bucket.Count)` = `len(bucket.Points)`
